// GENERATED — DO NOT EDIT.
//
// Produced by `dart run tool/generate_bindings.dart` from the Fortuna core's
// published C header. A wrong binding means a wrong header: fix it at the
// source in fortuna-api and regenerate (BR-36).
//
// ignore_for_file: type=lint, unused_element, camel_case_types

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// Generated bindings over the Fortuna core's C ABI.
///
/// DO NOT EDIT. Generated from native/include/fortuna_core.h by ffigen.
///
class FortunaBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FortunaBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FortunaBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  int fortuna_api_accounts_by_id_balance_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_accounts_by_id_balance_get(request_json, response_json);
  }

  late final _fortuna_api_accounts_by_id_balance_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_accounts_by_id_balance_get');
  late final _fortuna_api_accounts_by_id_balance_get =
      _fortuna_api_accounts_by_id_balance_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_accounts_by_id_delete(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_accounts_by_id_delete(request_json, response_json);
  }

  late final _fortuna_api_accounts_by_id_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_accounts_by_id_delete');
  late final _fortuna_api_accounts_by_id_delete =
      _fortuna_api_accounts_by_id_deletePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_accounts_by_id_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_accounts_by_id_get(request_json, response_json);
  }

  late final _fortuna_api_accounts_by_id_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_accounts_by_id_get');
  late final _fortuna_api_accounts_by_id_get =
      _fortuna_api_accounts_by_id_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_accounts_by_id_hard_delete(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_accounts_by_id_hard_delete(request_json, response_json);
  }

  late final _fortuna_api_accounts_by_id_hard_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_accounts_by_id_hard_delete');
  late final _fortuna_api_accounts_by_id_hard_delete =
      _fortuna_api_accounts_by_id_hard_deletePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_accounts_by_id_put(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_accounts_by_id_put(request_json, response_json);
  }

  late final _fortuna_api_accounts_by_id_putPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_accounts_by_id_put');
  late final _fortuna_api_accounts_by_id_put =
      _fortuna_api_accounts_by_id_putPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_accounts_by_id_restore_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_accounts_by_id_restore_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_accounts_by_id_restore_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_accounts_by_id_restore_post');
  late final _fortuna_api_accounts_by_id_restore_post =
      _fortuna_api_accounts_by_id_restore_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  /// Offline route exports generated from docs/openapi/fortuna.json.
  /// Request metadata uses {token, route, query, body}; body is the unchanged HTTP JSON body.
  /// Deliberately unavailable: /api/auth/** (Heimdall), /api/connections/** and
  /// GET /api/data-sources (Pluggy), POST /api/exchange-rates/sync (remote rate source),
  /// DELETE /api/users/{id} (no offline administrator), /api/me/consents/** (hosted
  /// external processing only), POST /api/local-accounts/password-reset (use recovery
  /// codes), and the HTTP-host health routes.
  /// Call fortuna_capabilities to discover the machine-readable availability contract.
  int fortuna_api_accounts_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_accounts_get(request_json, response_json);
  }

  late final _fortuna_api_accounts_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_accounts_get');
  late final _fortuna_api_accounts_get = _fortuna_api_accounts_getPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  /// Mirror `GET /api/accounts/{id}` for the authenticated native local account.
  ///
  /// Transport metadata and route values are carried in one JSON object:
  /// `{"token":"...","id":"uuid","includeDeleted":false}`. The response is the
  /// HTTP `DataOutput<FinancialAccountOutput?>` shape. Decimal fields are read from
  /// SQLite TEXT and emitted as invariant decimal strings without a float conversion.
  /// The response is library-owned and must be released with `fortuna_string_free`.
  int fortuna_api_accounts_get_by_id(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_accounts_get_by_id(request_json, response_json);
  }

  late final _fortuna_api_accounts_get_by_idPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_accounts_get_by_id');
  late final _fortuna_api_accounts_get_by_id =
      _fortuna_api_accounts_get_by_idPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_accounts_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_accounts_post(request_json, response_json);
  }

  late final _fortuna_api_accounts_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_accounts_post');
  late final _fortuna_api_accounts_post = _fortuna_api_accounts_postPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_attachments_by_id_delete(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_attachments_by_id_delete(request_json, response_json);
  }

  late final _fortuna_api_attachments_by_id_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_attachments_by_id_delete');
  late final _fortuna_api_attachments_by_id_delete =
      _fortuna_api_attachments_by_id_deletePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_attachments_by_id_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_attachments_by_id_get(request_json, response_json);
  }

  late final _fortuna_api_attachments_by_id_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_attachments_by_id_get');
  late final _fortuna_api_attachments_by_id_get =
      _fortuna_api_attachments_by_id_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_attachments_by_id_hard_delete(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_attachments_by_id_hard_delete(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_attachments_by_id_hard_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_attachments_by_id_hard_delete');
  late final _fortuna_api_attachments_by_id_hard_delete =
      _fortuna_api_attachments_by_id_hard_deletePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_audit_entries_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_audit_entries_get(request_json, response_json);
  }

  late final _fortuna_api_audit_entries_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_audit_entries_get');
  late final _fortuna_api_audit_entries_get = _fortuna_api_audit_entries_getPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_budgets_by_id_consumption_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_budgets_by_id_consumption_get(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_budgets_by_id_consumption_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_budgets_by_id_consumption_get');
  late final _fortuna_api_budgets_by_id_consumption_get =
      _fortuna_api_budgets_by_id_consumption_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_budgets_by_id_delete(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_budgets_by_id_delete(request_json, response_json);
  }

  late final _fortuna_api_budgets_by_id_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_budgets_by_id_delete');
  late final _fortuna_api_budgets_by_id_delete =
      _fortuna_api_budgets_by_id_deletePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_budgets_by_id_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_budgets_by_id_get(request_json, response_json);
  }

  late final _fortuna_api_budgets_by_id_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_budgets_by_id_get');
  late final _fortuna_api_budgets_by_id_get = _fortuna_api_budgets_by_id_getPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_budgets_by_id_put(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_budgets_by_id_put(request_json, response_json);
  }

  late final _fortuna_api_budgets_by_id_putPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_budgets_by_id_put');
  late final _fortuna_api_budgets_by_id_put = _fortuna_api_budgets_by_id_putPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_budgets_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_budgets_get(request_json, response_json);
  }

  late final _fortuna_api_budgets_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_budgets_get');
  late final _fortuna_api_budgets_get = _fortuna_api_budgets_getPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_budgets_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_budgets_post(request_json, response_json);
  }

  late final _fortuna_api_budgets_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_budgets_post');
  late final _fortuna_api_budgets_post = _fortuna_api_budgets_postPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_categories_by_id_delete(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_categories_by_id_delete(request_json, response_json);
  }

  late final _fortuna_api_categories_by_id_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_categories_by_id_delete');
  late final _fortuna_api_categories_by_id_delete =
      _fortuna_api_categories_by_id_deletePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_categories_by_id_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_categories_by_id_get(request_json, response_json);
  }

  late final _fortuna_api_categories_by_id_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_categories_by_id_get');
  late final _fortuna_api_categories_by_id_get =
      _fortuna_api_categories_by_id_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_categories_by_id_hard_delete(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_categories_by_id_hard_delete(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_categories_by_id_hard_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_categories_by_id_hard_delete');
  late final _fortuna_api_categories_by_id_hard_delete =
      _fortuna_api_categories_by_id_hard_deletePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_categories_by_id_put(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_categories_by_id_put(request_json, response_json);
  }

  late final _fortuna_api_categories_by_id_putPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_categories_by_id_put');
  late final _fortuna_api_categories_by_id_put =
      _fortuna_api_categories_by_id_putPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_categories_by_id_reassign_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_categories_by_id_reassign_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_categories_by_id_reassign_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_categories_by_id_reassign_post');
  late final _fortuna_api_categories_by_id_reassign_post =
      _fortuna_api_categories_by_id_reassign_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_categories_by_id_restore_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_categories_by_id_restore_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_categories_by_id_restore_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_categories_by_id_restore_post');
  late final _fortuna_api_categories_by_id_restore_post =
      _fortuna_api_categories_by_id_restore_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_categories_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_categories_get(request_json, response_json);
  }

  late final _fortuna_api_categories_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_categories_get');
  late final _fortuna_api_categories_get = _fortuna_api_categories_getPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_categories_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_categories_post(request_json, response_json);
  }

  late final _fortuna_api_categories_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_categories_post');
  late final _fortuna_api_categories_post = _fortuna_api_categories_postPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_counterparties_by_id_delete(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_counterparties_by_id_delete(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_counterparties_by_id_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_counterparties_by_id_delete');
  late final _fortuna_api_counterparties_by_id_delete =
      _fortuna_api_counterparties_by_id_deletePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_counterparties_by_id_merge_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_counterparties_by_id_merge_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_counterparties_by_id_merge_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_counterparties_by_id_merge_post');
  late final _fortuna_api_counterparties_by_id_merge_post =
      _fortuna_api_counterparties_by_id_merge_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_counterparties_by_id_put(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_counterparties_by_id_put(request_json, response_json);
  }

  late final _fortuna_api_counterparties_by_id_putPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_counterparties_by_id_put');
  late final _fortuna_api_counterparties_by_id_put =
      _fortuna_api_counterparties_by_id_putPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_counterparties_by_id_suggested_category_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_counterparties_by_id_suggested_category_get(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_counterparties_by_id_suggested_category_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_counterparties_by_id_suggested_category_get');
  late final _fortuna_api_counterparties_by_id_suggested_category_get =
      _fortuna_api_counterparties_by_id_suggested_category_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_counterparties_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_counterparties_get(request_json, response_json);
  }

  late final _fortuna_api_counterparties_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_counterparties_get');
  late final _fortuna_api_counterparties_get =
      _fortuna_api_counterparties_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_counterparties_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_counterparties_post(request_json, response_json);
  }

  late final _fortuna_api_counterparties_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_counterparties_post');
  late final _fortuna_api_counterparties_post =
      _fortuna_api_counterparties_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_credit_cards_by_id_delete(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_credit_cards_by_id_delete(request_json, response_json);
  }

  late final _fortuna_api_credit_cards_by_id_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_credit_cards_by_id_delete');
  late final _fortuna_api_credit_cards_by_id_delete =
      _fortuna_api_credit_cards_by_id_deletePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_credit_cards_by_id_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_credit_cards_by_id_get(request_json, response_json);
  }

  late final _fortuna_api_credit_cards_by_id_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_credit_cards_by_id_get');
  late final _fortuna_api_credit_cards_by_id_get =
      _fortuna_api_credit_cards_by_id_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_credit_cards_by_id_hard_delete(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_credit_cards_by_id_hard_delete(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_credit_cards_by_id_hard_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_credit_cards_by_id_hard_delete');
  late final _fortuna_api_credit_cards_by_id_hard_delete =
      _fortuna_api_credit_cards_by_id_hard_deletePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_credit_cards_by_id_put(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_credit_cards_by_id_put(request_json, response_json);
  }

  late final _fortuna_api_credit_cards_by_id_putPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_credit_cards_by_id_put');
  late final _fortuna_api_credit_cards_by_id_put =
      _fortuna_api_credit_cards_by_id_putPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_credit_cards_by_id_restore_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_credit_cards_by_id_restore_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_credit_cards_by_id_restore_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_credit_cards_by_id_restore_post');
  late final _fortuna_api_credit_cards_by_id_restore_post =
      _fortuna_api_credit_cards_by_id_restore_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_credit_cards_by_id_statements_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_credit_cards_by_id_statements_get(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_credit_cards_by_id_statements_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_credit_cards_by_id_statements_get');
  late final _fortuna_api_credit_cards_by_id_statements_get =
      _fortuna_api_credit_cards_by_id_statements_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_credit_cards_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_credit_cards_get(request_json, response_json);
  }

  late final _fortuna_api_credit_cards_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_credit_cards_get');
  late final _fortuna_api_credit_cards_get = _fortuna_api_credit_cards_getPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_credit_cards_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_credit_cards_post(request_json, response_json);
  }

  late final _fortuna_api_credit_cards_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_credit_cards_post');
  late final _fortuna_api_credit_cards_post = _fortuna_api_credit_cards_postPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_currencies_by_code_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_currencies_by_code_get(request_json, response_json);
  }

  late final _fortuna_api_currencies_by_code_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_currencies_by_code_get');
  late final _fortuna_api_currencies_by_code_get =
      _fortuna_api_currencies_by_code_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_currencies_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_currencies_get(request_json, response_json);
  }

  late final _fortuna_api_currencies_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_currencies_get');
  late final _fortuna_api_currencies_get = _fortuna_api_currencies_getPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_exchange_rates_convert_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_exchange_rates_convert_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_exchange_rates_convert_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_exchange_rates_convert_post');
  late final _fortuna_api_exchange_rates_convert_post =
      _fortuna_api_exchange_rates_convert_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_exchange_rates_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_exchange_rates_post(request_json, response_json);
  }

  late final _fortuna_api_exchange_rates_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_exchange_rates_post');
  late final _fortuna_api_exchange_rates_post =
      _fortuna_api_exchange_rates_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_exports_by_id_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_exports_by_id_get(request_json, response_json);
  }

  late final _fortuna_api_exports_by_id_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_exports_by_id_get');
  late final _fortuna_api_exports_by_id_get = _fortuna_api_exports_by_id_getPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_exports_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_exports_post(request_json, response_json);
  }

  late final _fortuna_api_exports_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_exports_post');
  late final _fortuna_api_exports_post = _fortuna_api_exports_postPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_goals_by_id_delete(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_goals_by_id_delete(request_json, response_json);
  }

  late final _fortuna_api_goals_by_id_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_goals_by_id_delete');
  late final _fortuna_api_goals_by_id_delete =
      _fortuna_api_goals_by_id_deletePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_goals_by_id_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_goals_by_id_get(request_json, response_json);
  }

  late final _fortuna_api_goals_by_id_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_goals_by_id_get');
  late final _fortuna_api_goals_by_id_get = _fortuna_api_goals_by_id_getPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_goals_by_id_progress_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_goals_by_id_progress_get(request_json, response_json);
  }

  late final _fortuna_api_goals_by_id_progress_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_goals_by_id_progress_get');
  late final _fortuna_api_goals_by_id_progress_get =
      _fortuna_api_goals_by_id_progress_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_goals_by_id_put(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_goals_by_id_put(request_json, response_json);
  }

  late final _fortuna_api_goals_by_id_putPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_goals_by_id_put');
  late final _fortuna_api_goals_by_id_put = _fortuna_api_goals_by_id_putPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_goals_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_goals_get(request_json, response_json);
  }

  late final _fortuna_api_goals_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_goals_get');
  late final _fortuna_api_goals_get = _fortuna_api_goals_getPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_goals_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_goals_post(request_json, response_json);
  }

  late final _fortuna_api_goals_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_goals_post');
  late final _fortuna_api_goals_post = _fortuna_api_goals_postPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_import_jobs_by_id_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_import_jobs_by_id_get(request_json, response_json);
  }

  late final _fortuna_api_import_jobs_by_id_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_import_jobs_by_id_get');
  late final _fortuna_api_import_jobs_by_id_get =
      _fortuna_api_import_jobs_by_id_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_import_jobs_by_id_records_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_import_jobs_by_id_records_get(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_import_jobs_by_id_records_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_import_jobs_by_id_records_get');
  late final _fortuna_api_import_jobs_by_id_records_get =
      _fortuna_api_import_jobs_by_id_records_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_import_jobs_by_id_retry_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_import_jobs_by_id_retry_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_import_jobs_by_id_retry_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_import_jobs_by_id_retry_post');
  late final _fortuna_api_import_jobs_by_id_retry_post =
      _fortuna_api_import_jobs_by_id_retry_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_import_jobs_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_import_jobs_get(request_json, response_json);
  }

  late final _fortuna_api_import_jobs_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_import_jobs_get');
  late final _fortuna_api_import_jobs_get = _fortuna_api_import_jobs_getPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_imports_excel_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_imports_excel_post(request_json, response_json);
  }

  late final _fortuna_api_imports_excel_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_imports_excel_post');
  late final _fortuna_api_imports_excel_post =
      _fortuna_api_imports_excel_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_imports_pdf_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_imports_pdf_post(request_json, response_json);
  }

  late final _fortuna_api_imports_pdf_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_imports_pdf_post');
  late final _fortuna_api_imports_pdf_post = _fortuna_api_imports_pdf_postPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_installment_plans_by_id_delete(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_installment_plans_by_id_delete(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_installment_plans_by_id_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_installment_plans_by_id_delete');
  late final _fortuna_api_installment_plans_by_id_delete =
      _fortuna_api_installment_plans_by_id_deletePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_installment_plans_by_id_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_installment_plans_by_id_get(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_installment_plans_by_id_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_installment_plans_by_id_get');
  late final _fortuna_api_installment_plans_by_id_get =
      _fortuna_api_installment_plans_by_id_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_installment_plans_by_id_restore_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_installment_plans_by_id_restore_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_installment_plans_by_id_restore_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_installment_plans_by_id_restore_post');
  late final _fortuna_api_installment_plans_by_id_restore_post =
      _fortuna_api_installment_plans_by_id_restore_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_installment_plans_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_installment_plans_post(request_json, response_json);
  }

  late final _fortuna_api_installment_plans_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_installment_plans_post');
  late final _fortuna_api_installment_plans_post =
      _fortuna_api_installment_plans_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_investments_by_id_delete(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_investments_by_id_delete(request_json, response_json);
  }

  late final _fortuna_api_investments_by_id_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_investments_by_id_delete');
  late final _fortuna_api_investments_by_id_delete =
      _fortuna_api_investments_by_id_deletePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_investments_by_id_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_investments_by_id_get(request_json, response_json);
  }

  late final _fortuna_api_investments_by_id_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_investments_by_id_get');
  late final _fortuna_api_investments_by_id_get =
      _fortuna_api_investments_by_id_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_investments_by_id_hard_delete(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_investments_by_id_hard_delete(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_investments_by_id_hard_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_investments_by_id_hard_delete');
  late final _fortuna_api_investments_by_id_hard_delete =
      _fortuna_api_investments_by_id_hard_deletePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_investments_by_id_movements_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_investments_by_id_movements_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_investments_by_id_movements_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_investments_by_id_movements_post');
  late final _fortuna_api_investments_by_id_movements_post =
      _fortuna_api_investments_by_id_movements_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_investments_by_id_put(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_investments_by_id_put(request_json, response_json);
  }

  late final _fortuna_api_investments_by_id_putPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_investments_by_id_put');
  late final _fortuna_api_investments_by_id_put =
      _fortuna_api_investments_by_id_putPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_investments_by_id_restore_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_investments_by_id_restore_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_investments_by_id_restore_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_investments_by_id_restore_post');
  late final _fortuna_api_investments_by_id_restore_post =
      _fortuna_api_investments_by_id_restore_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_investments_by_id_valuations_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_investments_by_id_valuations_get(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_investments_by_id_valuations_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_investments_by_id_valuations_get');
  late final _fortuna_api_investments_by_id_valuations_get =
      _fortuna_api_investments_by_id_valuations_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_investments_by_id_valuations_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_investments_by_id_valuations_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_investments_by_id_valuations_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_investments_by_id_valuations_post');
  late final _fortuna_api_investments_by_id_valuations_post =
      _fortuna_api_investments_by_id_valuations_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_investments_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_investments_get(request_json, response_json);
  }

  late final _fortuna_api_investments_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_investments_get');
  late final _fortuna_api_investments_get = _fortuna_api_investments_getPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_investments_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_investments_post(request_json, response_json);
  }

  late final _fortuna_api_investments_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_investments_post');
  late final _fortuna_api_investments_post = _fortuna_api_investments_postPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  /// Mirror `POST /api/local-accounts/authenticate` for the native local account.
  ///
  /// Request body: `{"name":"Local User","secret":"..."}`. The response uses the
  /// same `DataOutput<AuthenticateLocalAccountCommandOutput?>` JSON shape as HTTP.
  /// The request is copied only into zeroizing memory and is never logged.
  /// The response is library-owned and must be released with `fortuna_string_free`.
  int fortuna_api_local_accounts_authenticate(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_local_accounts_authenticate(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_local_accounts_authenticatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_local_accounts_authenticate');
  late final _fortuna_api_local_accounts_authenticate =
      _fortuna_api_local_accounts_authenticatePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_local_accounts_authenticate_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_local_accounts_authenticate_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_local_accounts_authenticate_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_local_accounts_authenticate_post');
  late final _fortuna_api_local_accounts_authenticate_post =
      _fortuna_api_local_accounts_authenticate_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_local_accounts_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_local_accounts_post(request_json, response_json);
  }

  late final _fortuna_api_local_accounts_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_local_accounts_post');
  late final _fortuna_api_local_accounts_post =
      _fortuna_api_local_accounts_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_local_accounts_recover_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_local_accounts_recover_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_local_accounts_recover_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_local_accounts_recover_post');
  late final _fortuna_api_local_accounts_recover_post =
      _fortuna_api_local_accounts_recover_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_local_accounts_recovery_codes_regenerate_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_local_accounts_recovery_codes_regenerate_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_local_accounts_recovery_codes_regenerate_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_local_accounts_recovery_codes_regenerate_post');
  late final _fortuna_api_local_accounts_recovery_codes_regenerate_post =
      _fortuna_api_local_accounts_recovery_codes_regenerate_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_me_data_export_by_job_id_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_me_data_export_by_job_id_get(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_me_data_export_by_job_id_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_me_data_export_by_job_id_get');
  late final _fortuna_api_me_data_export_by_job_id_get =
      _fortuna_api_me_data_export_by_job_id_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_me_data_export_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_me_data_export_post(request_json, response_json);
  }

  late final _fortuna_api_me_data_export_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_me_data_export_post');
  late final _fortuna_api_me_data_export_post =
      _fortuna_api_me_data_export_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_me_erasure_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_me_erasure_post(request_json, response_json);
  }

  late final _fortuna_api_me_erasure_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_me_erasure_post');
  late final _fortuna_api_me_erasure_post = _fortuna_api_me_erasure_postPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_me_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_me_get(request_json, response_json);
  }

  late final _fortuna_api_me_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_me_get');
  late final _fortuna_api_me_get = _fortuna_api_me_getPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_projections_cash_flow_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_projections_cash_flow_get(request_json, response_json);
  }

  late final _fortuna_api_projections_cash_flow_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_projections_cash_flow_get');
  late final _fortuna_api_projections_cash_flow_get =
      _fortuna_api_projections_cash_flow_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_projections_commitments_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_projections_commitments_get(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_projections_commitments_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_projections_commitments_get');
  late final _fortuna_api_projections_commitments_get =
      _fortuna_api_projections_commitments_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_recurring_transactions_by_id_delete(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_recurring_transactions_by_id_delete(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_recurring_transactions_by_id_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_recurring_transactions_by_id_delete');
  late final _fortuna_api_recurring_transactions_by_id_delete =
      _fortuna_api_recurring_transactions_by_id_deletePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_recurring_transactions_by_id_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_recurring_transactions_by_id_get(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_recurring_transactions_by_id_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_recurring_transactions_by_id_get');
  late final _fortuna_api_recurring_transactions_by_id_get =
      _fortuna_api_recurring_transactions_by_id_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_recurring_transactions_by_id_put(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_recurring_transactions_by_id_put(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_recurring_transactions_by_id_putPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_recurring_transactions_by_id_put');
  late final _fortuna_api_recurring_transactions_by_id_put =
      _fortuna_api_recurring_transactions_by_id_putPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_recurring_transactions_materialize_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_recurring_transactions_materialize_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_recurring_transactions_materialize_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_recurring_transactions_materialize_post');
  late final _fortuna_api_recurring_transactions_materialize_post =
      _fortuna_api_recurring_transactions_materialize_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_recurring_transactions_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_recurring_transactions_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_recurring_transactions_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_recurring_transactions_post');
  late final _fortuna_api_recurring_transactions_post =
      _fortuna_api_recurring_transactions_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_reports_aggregate_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_reports_aggregate_get(request_json, response_json);
  }

  late final _fortuna_api_reports_aggregate_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_reports_aggregate_get');
  late final _fortuna_api_reports_aggregate_get =
      _fortuna_api_reports_aggregate_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_reports_drill_down_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_reports_drill_down_get(request_json, response_json);
  }

  late final _fortuna_api_reports_drill_down_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_reports_drill_down_get');
  late final _fortuna_api_reports_drill_down_get =
      _fortuna_api_reports_drill_down_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_reports_net_position_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_reports_net_position_get(request_json, response_json);
  }

  late final _fortuna_api_reports_net_position_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_reports_net_position_get');
  late final _fortuna_api_reports_net_position_get =
      _fortuna_api_reports_net_position_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_reports_table_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_reports_table_post(request_json, response_json);
  }

  late final _fortuna_api_reports_table_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_reports_table_post');
  late final _fortuna_api_reports_table_post =
      _fortuna_api_reports_table_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_statements_by_id_close_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_statements_by_id_close_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_statements_by_id_close_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_statements_by_id_close_post');
  late final _fortuna_api_statements_by_id_close_post =
      _fortuna_api_statements_by_id_close_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_statements_by_id_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_statements_by_id_get(request_json, response_json);
  }

  late final _fortuna_api_statements_by_id_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_statements_by_id_get');
  late final _fortuna_api_statements_by_id_get =
      _fortuna_api_statements_by_id_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_statements_by_id_settle_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_statements_by_id_settle_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_statements_by_id_settle_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_statements_by_id_settle_post');
  late final _fortuna_api_statements_by_id_settle_post =
      _fortuna_api_statements_by_id_settle_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_tags_by_id_delete(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_tags_by_id_delete(request_json, response_json);
  }

  late final _fortuna_api_tags_by_id_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_tags_by_id_delete');
  late final _fortuna_api_tags_by_id_delete = _fortuna_api_tags_by_id_deletePtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_tags_by_id_put(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_tags_by_id_put(request_json, response_json);
  }

  late final _fortuna_api_tags_by_id_putPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_tags_by_id_put');
  late final _fortuna_api_tags_by_id_put = _fortuna_api_tags_by_id_putPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_tags_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_tags_get(request_json, response_json);
  }

  late final _fortuna_api_tags_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_tags_get');
  late final _fortuna_api_tags_get = _fortuna_api_tags_getPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_tags_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_tags_post(request_json, response_json);
  }

  late final _fortuna_api_tags_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_tags_post');
  late final _fortuna_api_tags_post = _fortuna_api_tags_postPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_transactions_by_id_attachments_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_transactions_by_id_attachments_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_transactions_by_id_attachments_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_transactions_by_id_attachments_post');
  late final _fortuna_api_transactions_by_id_attachments_post =
      _fortuna_api_transactions_by_id_attachments_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_transactions_by_id_delete(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_transactions_by_id_delete(request_json, response_json);
  }

  late final _fortuna_api_transactions_by_id_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_transactions_by_id_delete');
  late final _fortuna_api_transactions_by_id_delete =
      _fortuna_api_transactions_by_id_deletePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_transactions_by_id_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_transactions_by_id_get(request_json, response_json);
  }

  late final _fortuna_api_transactions_by_id_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_transactions_by_id_get');
  late final _fortuna_api_transactions_by_id_get =
      _fortuna_api_transactions_by_id_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_transactions_by_id_hard_delete(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_transactions_by_id_hard_delete(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_transactions_by_id_hard_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_transactions_by_id_hard_delete');
  late final _fortuna_api_transactions_by_id_hard_delete =
      _fortuna_api_transactions_by_id_hard_deletePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_transactions_by_id_put(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_transactions_by_id_put(request_json, response_json);
  }

  late final _fortuna_api_transactions_by_id_putPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_transactions_by_id_put');
  late final _fortuna_api_transactions_by_id_put =
      _fortuna_api_transactions_by_id_putPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_transactions_by_id_reconcile_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_transactions_by_id_reconcile_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_transactions_by_id_reconcile_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_transactions_by_id_reconcile_post');
  late final _fortuna_api_transactions_by_id_reconcile_post =
      _fortuna_api_transactions_by_id_reconcile_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_transactions_by_id_restore_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_transactions_by_id_restore_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_transactions_by_id_restore_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_transactions_by_id_restore_post');
  late final _fortuna_api_transactions_by_id_restore_post =
      _fortuna_api_transactions_by_id_restore_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_transactions_by_id_tags_by_tag_id_delete(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_transactions_by_id_tags_by_tag_id_delete(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_transactions_by_id_tags_by_tag_id_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_transactions_by_id_tags_by_tag_id_delete');
  late final _fortuna_api_transactions_by_id_tags_by_tag_id_delete =
      _fortuna_api_transactions_by_id_tags_by_tag_id_deletePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_transactions_by_id_tags_by_tag_id_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_transactions_by_id_tags_by_tag_id_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_transactions_by_id_tags_by_tag_id_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_transactions_by_id_tags_by_tag_id_post');
  late final _fortuna_api_transactions_by_id_tags_by_tag_id_post =
      _fortuna_api_transactions_by_id_tags_by_tag_id_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_transactions_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_transactions_get(request_json, response_json);
  }

  late final _fortuna_api_transactions_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_transactions_get');
  late final _fortuna_api_transactions_get = _fortuna_api_transactions_getPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_transactions_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_transactions_post(request_json, response_json);
  }

  late final _fortuna_api_transactions_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_transactions_post');
  late final _fortuna_api_transactions_post = _fortuna_api_transactions_postPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  int fortuna_api_transfers_by_id_delete(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_transfers_by_id_delete(request_json, response_json);
  }

  late final _fortuna_api_transfers_by_id_deletePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_transfers_by_id_delete');
  late final _fortuna_api_transfers_by_id_delete =
      _fortuna_api_transfers_by_id_deletePtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_transfers_by_id_get(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_transfers_by_id_get(request_json, response_json);
  }

  late final _fortuna_api_transfers_by_id_getPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_transfers_by_id_get');
  late final _fortuna_api_transfers_by_id_get =
      _fortuna_api_transfers_by_id_getPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_transfers_by_id_restore_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_transfers_by_id_restore_post(
      request_json,
      response_json,
    );
  }

  late final _fortuna_api_transfers_by_id_restore_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_transfers_by_id_restore_post');
  late final _fortuna_api_transfers_by_id_restore_post =
      _fortuna_api_transfers_by_id_restore_postPtr
          .asFunction<
            int Function(
              ffi.Pointer<ffi.Char>,
              ffi.Pointer<ffi.Pointer<ffi.Char>>,
            )
          >();

  int fortuna_api_transfers_post(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_api_transfers_post(request_json, response_json);
  }

  late final _fortuna_api_transfers_postPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_api_transfers_post');
  late final _fortuna_api_transfers_post = _fortuna_api_transfers_postPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  /// Describe every route available to offline callers and every deliberately absent route.
  /// Initialization is not required. The response is library-owned and must be released with
  /// `fortuna_string_free`.
  int fortuna_capabilities(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_capabilities(request_json, response_json);
  }

  late final _fortuna_capabilitiesPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_capabilities');
  late final _fortuna_capabilities = _fortuna_capabilitiesPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  /// Return 200 when SQLite can be opened, or 503 before initialization.
  /// The response is library-owned and must be released with `fortuna_string_free`.
  int fortuna_health(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_health(request_json, response_json);
  }

  late final _fortuna_healthPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_health');
  late final _fortuna_health = _fortuna_healthPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  /// Initialize the native core from a UTF-8 JSON object.
  ///
  /// Request: `{"databasePath":"/absolute/path/fortuna.db","localAuthEnabled":true,
  /// "tokenLifetimeSeconds":3600}`. The database is created and migrated on demand.
  /// Concurrent calls are supported; a second initialization returns 409.
  /// The response is always library-owned and must be released with `fortuna_string_free`.
  int fortuna_initialize(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_initialize(request_json, response_json);
  }

  late final _fortuna_initializePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_initialize');
  late final _fortuna_initialize = _fortuna_initializePtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  /// Shut down the current native core and invalidate all in-memory sessions.
  /// The response is library-owned and must be released with `fortuna_string_free`.
  int fortuna_shutdown(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_shutdown(request_json, response_json);
  }

  late final _fortuna_shutdownPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_shutdown');
  late final _fortuna_shutdown = _fortuna_shutdownPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();

  /// Release a response returned by any Fortuna native-core function.
  ///
  /// Passing NULL is a no-op. A non-NULL pointer must be released exactly once by
  /// the same loaded library instance; accessing it after this call is invalid.
  ///
  /// # Safety
  ///
  /// A non-NULL pointer must have been returned through a response out parameter by
  /// this exact loaded library instance and must not have been freed previously.
  void fortuna_string_free(ffi.Pointer<ffi.Char> response_json) {
    return _fortuna_string_free(response_json);
  }

  late final _fortuna_string_freePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char>)>>(
        'fortuna_string_free',
      );
  late final _fortuna_string_free = _fortuna_string_freePtr
      .asFunction<void Function(ffi.Pointer<ffi.Char>)>();

  /// Return the native core package version. Initialization is not required.
  /// The response is library-owned and must be released with `fortuna_string_free`.
  int fortuna_version(
    ffi.Pointer<ffi.Char> request_json,
    ffi.Pointer<ffi.Pointer<ffi.Char>> response_json,
  ) {
    return _fortuna_version(request_json, response_json);
  }

  late final _fortuna_versionPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int Function(
            ffi.Pointer<ffi.Char>,
            ffi.Pointer<ffi.Pointer<ffi.Char>>,
          )
        >
      >('fortuna_version');
  late final _fortuna_version = _fortuna_versionPtr
      .asFunction<
        int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<ffi.Char>>)
      >();
}

const int FORTUNA_STATUS_ACCEPTED = 202;

const int FORTUNA_STATUS_BAD_REQUEST = 400;

const int FORTUNA_STATUS_CONFLICT = 409;

const int FORTUNA_STATUS_CREATED = 201;

const int FORTUNA_STATUS_INTERNAL_ERROR = 500;

const int FORTUNA_STATUS_NOT_FOUND = 404;

const int FORTUNA_STATUS_NOT_INITIALIZED = 503;

const int FORTUNA_STATUS_OK = 200;

const int FORTUNA_STATUS_UNAUTHORIZED = 401;
